### PR TITLE
tests: add remaining samples

### PR DESCRIPTION
**Pull request by lukateras**
### Status

Sourced from http://cdemu.sourceforge.net/about/libmirage/

Currently supported image formats:
* [x] Alcohol 120% (MDS, **MDX**) image format
MDX is a monolithic version of MDF/MDS. Couldn't get Alcohol 120% to roundtrip.
* [ ] BlindWrite 5/6 (B5T, B6T) image format
I wonder if .b5t and .b5i is the same format. We have app-cdr/b5i2iso in the tree. I couldn't find an option in BlindWrite 6 to convert the base image without any modifications.
* [x] CloneCD (CCD, SUB, IMG) image format
Made using UltraISO. I couldn't get the original converter (CloneCD) to roundtrip.
* [x] CDRwin (CUE, BIN) image format
* [x] Cdrdao's (TOC, BIN) image format
* [ ] DiscJuggler (CDI) image format
Couldn't get anything useful out of DiscJuggler 6 other than seemingly useless .cdj files.
* [ ] Easy CD Creator (CIF) image format
I've used Roxio Easy CD Creator, and couldn't roundtrip `00_input.iso`.
* [ ] Easy Media Creator/WinOnCD (C2D) file format
Same here (also by Roxio).
* [x] ISO-9660 (ISO) image format
* [x] Nero Burning ROM (NRG) image format
* [x] ReadCD (TOC, BIN) image format
* ~Universal Disk Format (UDF) image format~
I think that UDF is not an image format, but a file system.
* [x] XCDRoast (TOC, BIN) image format

Currently supported container formats:
* [x] Apple disk (DMG, CDR) image format
There is not much documentation about this, but judging by `hdiutil` behavior, cdr = iso
* [x] Compressed ISO (CSO) image format
* [x] Error Code Modeller (ECM) container format
* [x] gBurner (GBI) image format
* ~GZip (GZ) container format~ **?**
* [x] PowerISO (DAA) image format
* ~libSndFile supported formats (WAV, FLAC etc.)~
* [x] UltraISO's (ISZ) image format
* ~Xz (XZ) container format~ **?**

### CODE REVIEW

**Comment by lukateras** [comment]
@mgorny I've tried to get all samples and only got 4. There are 4 more formats left, but they're problematic (as in, I'll need to use a different base ISO to add tests for them).

**Comment by mgorny** [comment]
Thanks a lot!

**Comment by mgorny** [comment]
What do you mean by 'a different base ISO'? Do you mean the current .iso somehow makes them unhappy or that they aren't capable of accepting .iso as an input and you'd have to record it or sth? Have you tried putting the .iso into a virtual drive and trying to rip it afterwards?

**Comment by lukateras** [comment]
They all seem to modify the base iso either by adding their own metadata, or by changing the file system (`00_input.iso` uses Rock Ridge attributes, and they seem to drop it). When I convert these back to iso, they result in a different iso file.

**Comment by mgorny** [comment]
Hmm, it seems that you've found a few bugs in libMirage as well:

```
FAIL: 01_ultraiso-9.6.6.3300.isz
================================

../../tests/01_ultraiso-9.6.6.3300.isz -> ../../tests/01_ultraiso-9.6.6.3300.isz.iso
+ case "$(basename "${input}")" in
++ basename ../../tests/01_ultraiso-9.6.6.3300.isz
+ ../mirage2iso -q -s 0 -p test ../../tests/01_ultraiso-9.6.6.3300.isz ../../tests/01_ultraiso-9.6.6.3300.isz.iso

(mirage2iso:447): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed

(mirage2iso:447): GLib-GObject-WARNING **: invalid cast from 'MirageFilterStreamIsz' to 'GFilterInputStream'

(mirage2iso:447): GLib-GIO-CRITICAL **: g_filter_input_stream_get_base_stream: assertion 'G_IS_FILTER_INPUT_STREAM (stream)' failed

(mirage2iso:447): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
../../tests/perform-test: line 11:   447 Segmentation fault      (core dumped) "${m2i}" -q -s 0 -p test "${input}" "${output}"
FAIL 01_ultraiso-9.6.6.3300.isz (exit status: 139)
```

**Comment by lukateras** [comment]
Interesting. Well, they should at least use your test suite :-) Or even use mirage2iso to test that libmirage works correctly. And I hope they won't break API in the future (it looks they've done that several times).

I've used UltraISO to get .isz sample, and UltraISO is the original creator of this format.

**Comment by mgorny** [comment]
I've also had to remove .sub from tests — but I presume that's subchannel data, so not really useful as input file alone ;-).

UDZO seems to fail as well:

```
FAIL: 01_hdiutil_udzo.dmg
=========================

../../tests/01_hdiutil_udzo.dmg -> ../../tests/01_hdiutil_udzo.dmg.iso
+ case "$(basename "${input}")" in
++ basename ../../tests/01_hdiutil_udzo.dmg
+ ../mirage2iso -q -s 0 -p test ../../tests/01_hdiutil_udzo.dmg ../../tests/01_hdiutil_udzo.dmg.iso

(mirage2iso:4577): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed

(mirage2iso:4577): GLib-GObject-WARNING **: invalid cast from 'MirageFilterStreamDmg' to 'GFilterInputStream'

(mirage2iso:4577): GLib-GIO-CRITICAL **: g_filter_input_stream_get_base_stream: assertion 'G_IS_FILTER_INPUT_STREAM (stream)' failed

(mirage2iso:4577): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
../../tests/perform-test: line 11:  4577 Segmentation fault      (core dumped) "${m2i}" -q -s 0 -p test "${input}" "${output}"
FAIL 01_hdiutil_udzo.dmg (exit status: 139)
```

**Comment by lukateras** [comment]
Both isz and UDZO use zlib to compress image data. Do any other dmg samples pass the test? UDZO is the default dmg format. ULFO uses lzfse, and is relatively new (available since macOS 10.11, released two years ago), UDBZ uses bzip2, UDCO uses ADC.

**Comment by mgorny** [comment]
Nope, all of them fail. I guess it's time we report that upstream.

I've pushed your four commits with minor modifications. If you're still interested in testing the other tools, feel free to add additional input files. if possible, try to avoid adding too many of them — maybe see if you get one through all of them you get some kind of 'final' version that fits all ;-). Then add the extra files as `00_program_input.iso` and tests as `0n_*` with n being unique for each input file (it's how it's done right now — 04* tests use `00_second.iso`).

**Comment by lukateras** [comment]
DiscJuggler et al. don't seem to work correctly on Windows Server 2017, so I'll try to get the remaining samples on my Windows 2000 virtual machine. It will be tomorrow, I guess.

If you plan to send a bug report, CC me :-)

**Comment by mgorny** [comment]
https://sourceforge.net/p/cdemu/bugs/105/

**Pull request closed without merging**
