### PR TITLE
Add gbi sample to tests

### PR DESCRIPTION
**Pull request by lukateras**
gentoo/gentoo#4669 :-)

Could you make a new tarball that includes this sample so I can use it in app-cdr/daa2iso ebuild?

### CODE REVIEW

**Comment by mgorny** [comment]
I'll look whether we can add a few more formats, whether there are any pending commits and then wrap up some tarball.

**Comment by lukateras** [comment]
Sure! It probably makes sense to have at least one file for each format supported by libmirage. The problem is to get it to roundtrip without any changes (I didn't have any luck with CloneCD (ccd), for example). I'll try to send you a few more!

**Comment by mgorny** [comment]
Thanks. If possible, try to use the original Windows tools not to accidentally rely on reimplementation bugs ;-).

**Comment by lukateras** [comment]
Sure, I've only used original Windows tools so far.

**Pull request closed without merging**
